secrets:
  mysql_root_password:
    file: ./mysql_root_password.txt

services:
  nginx:
    image: nginx:1.21.6
    ports:
      - "4001:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./www:/var/www/html
    networks:
      - frontend
      - backend

  php:
    build: .
    volumes:
      - ./www:/var/www/html
    networks:
      - backend

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
    secrets:
      - mysql_root_password
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: user
      PMA_PASSWORD_FILE: /run/secrets/mysql_root_password
    ports:
      - "6001:80"
    networks:
      - backend
    secrets:
      - mysql_root_password

networks:
  backend:
    driver: bridge
